import { EVIDENCE_ITEMS } from "../data/operations.js";
import { POLICIES, POLICY_STATUS } from "../data/operations.js";
import { FINDINGS, FINDING_SEVERITY } from "../data/assurance.js";

export function downloadAuditPack() {
  const now = new Date().toLocaleString("en-US", { dateStyle: "long", timeStyle: "short" });
  const row = (cells) => `<tr>${cells.map((c) => `<td>${c}</td>`).join("")}</tr>`;

  const evidenceRows = EVIDENCE_ITEMS.map((e) =>
    row([e.name, e.control, e.type, e.updated, e.freshness === "fresh" ? "Fresh" : "Stale"])
  ).join("");

  const policyRows = POLICIES.map((p) =>
    row([p.name, p.version, POLICY_STATUS[p.status].label, p.attestation != null ? p.attestation + "%" : "—", p.nextReview])
  ).join("");

  const findingRows = FINDINGS.map((f) =>
    row([f.id, f.title, f.control, FINDING_SEVERITY[f.severity].label, f.status.replace("-", " ")])
  ).join("");

  const html = `<!doctype html><html><head><meta charset="utf-8"><title>DU-NZO Audit Pack</title>
<style>
  body{font-family:-apple-system,Segoe UI,Roboto,Arial,sans-serif;color:#0f172a;margin:0;padding:40px;line-height:1.5}
  h1{font-size:26px;margin:0 0 4px}.sub{color:#64748b;font-size:13px;margin:0 0 28px}
  h2{font-size:16px;margin:32px 0 10px;padding-bottom:6px;border-bottom:2px solid #8B7CFF}
  table{width:100%;border-collapse:collapse;font-size:12px;margin-bottom:8px}
  th,td{text-align:left;padding:7px 10px;border-bottom:1px solid #e2e8f0}
  th{background:#f8fafc;color:#475569;text-transform:uppercase;font-size:10px;letter-spacing:.06em}
  .badge{display:inline-block;padding:2px 8px;border-radius:999px;background:#eef2ff;color:#5B4BE0;font-weight:600;font-size:11px}
  .foot{margin-top:40px;color:#94a3b8;font-size:11px;border-top:1px solid #e2e8f0;padding-top:12px}
</style></head><body>
  <h1>DU-NZO — Audit Evidence Pack</h1>
  <p class="sub">Generated ${now} · Demo Organization · Sample data</p>
  <span class="badge">ISO/IEC 27001 · SOC 2 · DPDPA · ISO/IEC 42001</span>

  <h2>Evidence (${EVIDENCE_ITEMS.length} artefacts)</h2>
  <table><thead><tr><th>Artefact</th><th>Control</th><th>Type</th><th>Updated</th><th>Freshness</th></tr></thead><tbody>${evidenceRows}</tbody></table>

  <h2>Policies (${POLICIES.length})</h2>
  <table><thead><tr><th>Policy</th><th>Version</th><th>Status</th><th>Attestation</th><th>Next review</th></tr></thead><tbody>${policyRows}</tbody></table>

  <h2>Findings (${FINDINGS.length})</h2>
  <table><thead><tr><th>ID</th><th>Finding</th><th>Control</th><th>Severity</th><th>Status</th></tr></thead><tbody>${findingRows}</tbody></table>

  <p class="foot">This pack was generated by the DU-NZO Platform preview. Sample data for demonstration only.</p>
</body></html>`;

  const blob = new Blob([html], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `dunzo-audit-pack-${new Date().toISOString().slice(0, 10)}.html`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
